DROP TABLE OUTLAST_DATA;
DROP SEQUENCE SEQ_OUTLAST_DATA_ID;
CREATE SEQUENCE SEQ_OUTLAST_DATA_ID
    START WITH 1
    INCREMENT BY 1024 CACHE 1024;
CREATE TABLE OUTLAST_DATA
(
    ID      BIGINT PRIMARY KEY,
    SOURCE  VARCHAR(6),
    TARGET  VARCHAR(6),
    CHANNEL CHAR(36),
    TYPE    VARCHAR(6),
    CONTENT VARCHAR(3584)
);
CREATE INDEX INDEX_OUTLAST_DATA_CHANNEL
    ON OUTLAST_PROXY (CHANNEL);