DROP TABLE {DATA_TABLE};
DROP SEQUENCE SEQ_{DATA_TABLE}_ID;
CREATE SEQUENCE SEQ_{DATA_TABLE}_ID
    START WITH 1
    INCREMENT BY 1 CACHE 32768;
CREATE TABLE {DATA_TABLE}
(
    ID      BIGINT PRIMARY KEY,
    SOURCE  VARCHAR(6),
    TARGET  VARCHAR(6),
    CHANNEL CHAR(36),
    TYPE    VARCHAR(6),
    CONTENT VARCHAR(3584)
);
CREATE INDEX INDEX_{DATA_TABLE}_CHANNEL
    ON {DATA_TABLE} (CHANNEL);