DROP TABLE OUTLAST_TUNNEL_DATA;
DROP SEQUENCE SEQ_OUTLAST_TUNNEL_DATA_ID;

CREATE SEQUENCE SEQ_OUTLAST_TUNNEL_DATA_ID
    START WITH 1
    INCREMENT BY 1024 CACHE 1024;

CREATE TABLE OUTLAST_TUNNEL_DATA
(
    ID      BIGINT PRIMARY KEY,
    SOURCE  VARCHAR(36),
    TARGET  VARCHAR(36),
    CHANNEL CHAR(36),
    BATCH   CHAR(36),
    SERIAL  INT,
    TOTAL   INT,
    CONTENT VARCHAR(3584)
);

CREATE INDEX INDEX_OUTLAST_TUNNEL_DATA_CHANNEL
    ON OUTLAST_TUNNEL_DATA (CHANNEL);
CREATE INDEX INDEX_OUTLAST_TUNNEL_DATA_BATCH
    ON OUTLAST_TUNNEL_DATA (BATCH);
